version: '3'

services:
  reverse-proxy:
    image: traefik:1.7.3-alpine
    command: --docker \
             --acme.email=${TRAEFIK_ACME_EMAIL}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # The Web UI (enabled by --api)
    labels:
      - "traefik.frontend.rule=${TRAEFIK_MONITOR}"
      - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # So that Traefik can listen to the Docker events
      - /home/admin/docker/infra/traefik.toml:/traefik.toml
      - /home/admin/docker/infra/acme.json:/acme.json
    networks:
      - proxy
      - default

networks:
  proxy:
    external:
      name: proxy